filter: {
  3 point color balance: /usr/lib/frei0r-1/three_point_balance.so,
  # crashes
  # 3dflippo: /usr/lib/frei0r-1/3dflippo.so,
  B: /usr/lib/frei0r-1/B.so,
  Baltan: /usr/lib/frei0r-1/baltan.so,
  # crashes
  # BgSubtract0r: /usr/lib/frei0r-1/bgsubtract0r.so,
  Brightness: /usr/lib/frei0r-1/brightness.so,
  Cartoon: /usr/lib/frei0r-1/cartoon.so,
  Color Distance: /usr/lib/frei0r-1/colordistance.so,
  Contrast0r: /usr/lib/frei0r-1/contrast0r.so,
  # Took 100% cpu and couldn't switch out of it
  # Curves: /usr/lib/frei0r-1/curves.so,
  Defish0r: /usr/lib/frei0r-1/defish0r.so,
  # Circular fixed delay- parameters to change this would be nice
  # (also make a generalized per-pixel delay map in image_manip)
  Delaygrab: /usr/lib/frei0r-1/delaygrab.so,
  Distort0r: /usr/lib/frei0r-1/distort0r.so,
  Edgeglow: /usr/lib/frei0r-1/edgeglow.so,
  Equaliz0r: /usr/lib/frei0r-1/equaliz0r.so,
  # cv exception
  # FaceBl0r: /usr/lib/frei0r-1/facebl0r.so,
  Flippo: /usr/lib/frei0r-1/flippo.so,
  G: /usr/lib/frei0r-1/G.so,
  Gamma: /usr/lib/frei0r-1/gamma.so,
  Glitch0r: /usr/lib/frei0r-1/glitch0r.so,
  Glow: /usr/lib/frei0r-1/glow.so,
  Hueshift0r: /usr/lib/frei0r-1/hueshift0r.so,
  IIR blur: /usr/lib/frei0r-1/IIRblur.so,
  Invert0r: /usr/lib/frei0r-1/invert0r.so,
  K-Means Clustering: /usr/lib/frei0r-1/cluster.so,
  Lens Correction: /usr/lib/frei0r-1/lenscorrection.so,
  # LetterB0xed: /usr/lib/frei0r-1/letterb0xed.so,
  # Shows box with levels in it
  # Levels: /usr/lib/frei0r-1/levels.so,
  Light Graffiti: /usr/lib/frei0r-1/lightgraffiti.so,
  # Luminance: /usr/lib/frei0r-1/luminance.so,
  Mask0Mate: /usr/lib/frei0r-1/mask0mate.so,
  Medians: /usr/lib/frei0r-1/medians.so,
  NDVI filter: /usr/lib/frei0r-1/ndvi.so,
  # Nervous is good
  Nervous: /usr/lib/frei0r-1/nervous.so,
  Nikon D90 Stairstepping fix: /usr/lib/frei0r-1/d90stairsteppingfix.so,
  Perspective: /usr/lib/frei0r-1/perspective.so,
  R: /usr/lib/frei0r-1/R.so,
  # TODO(lucasw) make the lines and values optional
  RGB-Parade: /usr/lib/frei0r-1/rgbparade.so,
  SOP_Sat: /usr/lib/frei0r-1/sopsat.so,
  Saturat0r: /usr/lib/frei0r-1/saturat0r.so,
  Scale0Tilt: /usr/lib/frei0r-1/scale0tilt.so,
  Sharpness: /usr/lib/frei0r-1/sharpness.so,
  Sobel: /usr/lib/frei0r-1/sobel.so,
  Squareblur: /usr/lib/frei0r-1/squareblur.so,
  TehRoxx0r: /usr/lib/frei0r-1/tehroxx0r.so,
  Threshold0r: /usr/lib/frei0r-1/threshold0r.so,
  Timeout indicator: /usr/lib/frei0r-1/timeout.so,
  Tint0r: /usr/lib/frei0r-1/tint0r.so,
  Transparency: /usr/lib/frei0r-1/transparency.so,
  Twolay0r: /usr/lib/frei0r-1/twolay0r.so,
  # Vectorscope: /usr/lib/frei0r-1/vectorscope.so,
  Vertigo: /usr/lib/frei0r-1/vertigo.so,
  Vignette: /usr/lib/frei0r-1/vignette.so,
  White Balance: /usr/lib/frei0r-1/balanc0r.so,
  White Balance (LMS space): /usr/lib/frei0r-1/colgate.so,
  alpha0ps: /usr/lib/frei0r-1/alpha0ps.so,
  alphagrad: /usr/lib/frei0r-1/alphagrad.so,
  alphaspot: /usr/lib/frei0r-1/alphaspot.so,
  bluescreen0r: /usr/lib/frei0r-1/bluescreen0r.so,
  bw0r: /usr/lib/frei0r-1/bw0r.so,
  c0rners: /usr/lib/frei0r-1/c0rners.so,
  cairogradient: /usr/lib/frei0r-1/cairogradient.so,
  cairoimagegrid: /usr/lib/frei0r-1/cairoimagegrid.so,
  coloradj_RGB: /usr/lib/frei0r-1/coloradj_RGB.so,
  colorhalftone: /usr/lib/frei0r-1/colorhalftone.so,
  colorize: /usr/lib/frei0r-1/colorize.so,
  colortap: /usr/lib/frei0r-1/colortap.so,
  delay0r: /usr/lib/frei0r-1/delay0r.so,
  dither: /usr/lib/frei0r-1/dither.so,
  # Emboss is really cool
  emboss: /usr/lib/frei0r-1/emboss.so,
  hqdn3d: /usr/lib/frei0r-1/hqdn3d.so,
  keyspillm0pup: /usr/lib/frei0r-1/keyspillm0pup.so,
  nosync0r: /usr/lib/frei0r-1/nosync0r.so,
  opencvfacedetect: /usr/lib/frei0r-1/facedetect.so,
  pixeliz0r: /usr/lib/frei0r-1/pixeliz0r.so,
  posterize: /usr/lib/frei0r-1/posterize.so,
  # pr0be: /usr/lib/frei0r-1/pr0be.so,
  # pr0file: /usr/lib/frei0r-1/pr0file.so,
  primaries: /usr/lib/frei0r-1/primaries.so,
  rgbnoise: /usr/lib/frei0r-1/rgbnoise.so,
  rgbsplit0r: /usr/lib/frei0r-1/rgbsplit0r.so,
  scanline0r: /usr/lib/frei0r-1/scanline0r.so,
  select0r: /usr/lib/frei0r-1/select0r.so,
  sigmoidaltransfer: /usr/lib/frei0r-1/sigmoidaltransfer.so,
  softglow: /usr/lib/frei0r-1/softglow.so,
  spillsupress: /usr/lib/frei0r-1/spillsupress.so,
  threelay0r: /usr/lib/frei0r-1/threelay0r.so,
  none: none,
}
