source: {
  none: none,
  Ising0r: /usr/lib/frei0r-1/ising0r.so,
  Lissajous0r: /usr/lib/frei0r-1/lissajous0r.so,
  Nois0r: /usr/lib/frei0r-1/nois0r.so,
  Partik0l: /usr/lib/frei0r-1/partik0l.so,
  Plasma: /usr/lib/frei0r-1/plasma.so,
  onecol0r: /usr/lib/frei0r-1/onecol0r.so,
  test_pat_B: /usr/lib/frei0r-1/test_pat_B.so,
  test_pat_C: /usr/lib/frei0r-1/test_pat_C.so,
  test_pat_G: /usr/lib/frei0r-1/test_pat_G.so,
  test_pat_I: /usr/lib/frei0r-1/test_pat_I.so,
  test_pat_L: /usr/lib/frei0r-1/test_pat_L.so,
  test_pat_R: /usr/lib/frei0r-1/test_pat_R.so,
}
